fix(workflows) try cache boot2docker iso

diff --git a/bin/bump-version b/bin/bump-version
--- a/bin/bump-version
+++ b/bin/bump-version
@@ -41,16 +41,16 @@ for platform in mojave arm64_big_sur; do
   echo "Building bottle..."
   bin/mkbottle "$version" "$platform" "$formula"
 
-  # echo "Uploading bottle to S3..."
-  # if ! aws s3 cp bottle.$platform.tar.gz "s3://materialize-homebrew/$formula-$version.$platform.bottle.tar.gz"; then
-  #   echo
-  #   echo "Uploading to S3 failed." >&2
-  #   echo "AWS CLI access is documented here: https://github.com/MaterializeInc/i2/blob/main/doc/aws-access.md" >&2
-  #   echo "Ask for any clarification in #release on Slack." >&2
-  #   echo "Note:"
-  #   echo "    You need to be logged in to the mz-core-admin account"
-  #   exit 1
-  # fi
+  echo "Uploading bottle to S3..."
+  if ! aws s3 cp bottle.$platform.tar.gz "s3://materialize-homebrew/$formula-$version.$platform.bottle.tar.gz"; then
+    echo
+    echo "Uploading to S3 failed." >&2
+    echo "AWS CLI access is documented here: https://github.com/MaterializeInc/i2/blob/main/doc/aws-access.md" >&2
+    echo "Ask for any clarification in #release on Slack." >&2
+    echo "Note:"
+    echo "    You need to be logged in to the mz-core-admin account"
+    exit 1
+  fi
 
   echo "Updating formula for new bottle SHA..."
   bottle_sha=$(openssl sha256 < bottle.$platform.tar.gz | sed -e 's/(stdin)= //' -e 's/^SHA256//')
@@ -62,11 +62,11 @@ EOF
   mv Formula/$formula.rb{.new,}
 done
 
-# echo
-# echo "Committing changes on new branch..."
-# echo
-# git checkout -b "v$version"
-# git commit -am "v$version"
+echo
+echo "Committing changes on new branch..."
+echo
+git checkout -b "v$version"
+git commit -am "v$version"
 
 # Clean up only if everything was successful, to ease debugging failures.
 rm bottle.*.tar.gz
