Publish M1 bottles

diff --git a/bin/bump-version b/bin/bump-version
--- a/bin/bump-version
+++ b/bin/bump-version
@@ -36,28 +36,30 @@ sed -f /dev/stdin Formula/materialized.rb > Formula/materialized.rb.new <<EOF
 EOF
 mv Formula/materialized.rb{.new,}
 
-echo "Building bottle..."
-bin/mkbottle "$version"
+for platform in mojave arm64_big_sur; do
+  echo "Building bottle..."
+  bin/mkbottle "$version" "$platform"
 
-echo "Uploading bottle to S3..."
-if ! aws s3 cp bottle.tar.gz "s3://materialize-homebrew/materialized-$version.mojave.bottle.tar.gz"; then
-  echo
-  echo "Uploading to S3 failed." >&2
-  echo "AWS CLI access is documented here: https://github.com/MaterializeInc/i2/blob/main/doc/aws-access.md" >&2
-  echo "Ask for any clarification in #release on Slack." >&2
-  echo "Note:"
-  echo "    You need to be logged in to the mz-core-admin account"
-  exit 1
-fi
+  echo "Uploading bottle to S3..."
+  if ! aws s3 cp bottle.$platform.tar.gz "s3://materialize-homebrew/materialized-$version.$platform.bottle.tar.gz"; then
+    echo
+    echo "Uploading to S3 failed." >&2
+    echo "AWS CLI access is documented here: https://github.com/MaterializeInc/i2/blob/main/doc/aws-access.md" >&2
+    echo "Ask for any clarification in #release on Slack." >&2
+    echo "Note:"
+    echo "    You need to be logged in to the mz-core-admin account"
+    exit 1
+  fi
 
-echo "Updating formula for new bottle SHA..."
-bottle_sha=$(openssl sha256 < bottle.tar.gz | sed 's/(stdin)= //')
-echo "Bottle SHA-256: $bottle_sha"
-sed -f /dev/stdin Formula/materialized.rb > Formula/materialized.rb.new <<EOF
-/^    sha256 mojave: .*/c\\
-\    sha256 mojave: "$bottle_sha"
+  echo "Updating formula for new bottle SHA..."
+  bottle_sha=$(openssl sha256 < bottle.$platform.tar.gz | sed 's/(stdin)= //')
+  echo "Bottle SHA-256: $bottle_sha"
+  sed -f /dev/stdin Formula/materialized.rb > Formula/materialized.rb.new <<EOF
+/^    sha256 $platform: .*/c\\
+\    sha256 $platform: "$bottle_sha"
 EOF
-mv Formula/materialized.rb{.new,}
+  mv Formula/materialized.rb{.new,}
+done
 
 echo
 echo "Committing changes on new branch..."
@@ -66,7 +68,7 @@ git checkout -b "v$version"
 git commit -am "v$version"
 
 # Clean up only if everything was successful, to ease debugging failures.
-rm bottle.tar.gz
+rm bottle.*.tar.gz
 
 echo
 echo "Changes complete! Create a PR with the current branch: v$version"
